version: '3.1'
services:
#  sonarqube:
#    image: sonarqube
#    ports:
#      - 9000:9000
#    networks:
#      - albusNet

  portainer:
    image: portainer/portainer:latest
    ports:
     - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks:
      - albusNet

  postgreSQL:
    image: postgres
#    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: albus
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    ports:
      - 5433:5432
    networks:
          - albusNet

volumes:
  portainerdata:

networks:
  albusNet: